name: Compile LaTeX

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up LaTeX environment
        uses: dante-ev/latex-action@latest

      - name: Compile LaTeX document
        run: |
          latexmk -pdf -silent -interaction=nonstopmode main.tex
          mv main.pdf numpde-notes.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: numpde-notes.pdf
